[phases.setup]
nixPkgs = ['openjdk21', 'gradle']

[phases.build]
cmds = ['gradle clean build -x test --no-daemon']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/*.jar'
