m[phases.setup]
nixPkgs = ['jdk21']

[phases.install]
cmds = ['chmod +x gradlew']

[phases.build]
cmds = ['./gradlew clean build -x test']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/*.jar'
