[phases.setup]
nixPkgs = ['openjdk21']

[phases.build]
cmds = ['./gradlew clean build -x test --no-daemon']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/*.jar'
